name: Validar HTML con HTMLHint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validar-html:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar HTMLHint
      run: npm install -g htmlhint

    - name: Ejecutar HTMLHint
      run: htmlhint .
